language: python
python:
  - "2.7"
cache: apt
services:
  - rabbitmq
  - redis-server
addons:
  postgresql: "9.3"
before_script:
  - pushd js/angular
  -     npm install -g bower grunt-cli yo generator-angular --silent
  -     gem install -q -v 3.3.4 sass
  -     gem install -q -v 0.12.5 compass
  - popd
  - pushd deployment
  -     sudo ./provision.sh travis
  - popd
  - pushd js/angular
  -     bower install --config.interactive=false
  -     npm install
  -     grunt build
  - popd
env:
  global:
  - secure: JPqVgULkqa5ny9k3+TZsWCJHgG1uP4uMP3shs0VGA7vwVINhJsACBCOmGvTvMX/N7+eZmTlxLJlHZU2MkH0nIyypQ0C71ZkHZURUQ505yqR0n+/8O4HnmVACM1ZnP9YDauy2yAzHVHs9W7ZaqMJym9qyJoqMpY5VEXK35WFPyvk=
  - secure: OMZ1U4UA/VQxexgM6hWV+EcMgZAK6aHDg47cpKs50Smcg+ZXJiF7SlxqPPuXaQgYxkMb+9Qf6r6ZQ3uhxdfGkcz14pC6C8elwqz2CcrCv3IYoAjdvZ4EEV3vnTiJ96VKbwCOV5EM0wTRqdYd3GPg0JWPYNrxyq+hPKojmQ3wl0I=
script:
  - pushd python/django
  -     sudo python manage.py test --noinput
  - popd
  - pushd js/angular
  -    grunt test
  - popd
  - pushd geotrellis
  -     sudo ./sbt test
  - popd
